sudo: required

services:
  - docker

before_install:
  - docker build -t bkramer2012/swim-office-react-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true bkramer2012/swim-office-react-test npm test -- --coverage

after_success:
  - docker build -t bkramer2012/swim-office-frontend ./frontend
  - docker build -t bkramer2012/swim-office-nginx ./nginx
  - docker build -t bkramer2012/swim-office-backend ./backend
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push bkramer2012/swim-office-frontend
  - docker push bkramer2012/swim-office-nginx
  - docker push bkramer2012/swim-office-backend

#deploy:
#  provider: elasticbeanstalk
#  region: us-west-1
#  app: multi-docker
#  env: MultiDocker-env
#  bucket_name: elasticbeanstalk-us-west-1-306476627547
#  bucket_path: docker-multi
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY
